baseURL = "https://beta.steckschwein.de"
languageCode = "en-us"
theme = "terminal"
title = "Steckschwein"

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params.twitter]
  creator = "steckschwein"
  site = ""

[languages]
  [languages.en]
    title = "Steckschwein"
    weight = 1
    contentDir = "content"

    [languages.en.params.logo]
      logoText = "Steckschwein"
      logoHomeLink = "/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  #contentTypeName = "posts"

  themeColor = "green"
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  featured_image = "images/cropped-steckos.jpg"
  description = "Never trust a computer you did not build yourself."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/steckschwein"
