baseurl = "https://www.steckschwein.de/"
languageCode = "en-us"
theme = ["Mainroad"]
paginate = 5
#sectionPagesMenu = "main"

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = true
  # favicon = "s"
  twitter.site="@steckschwein"
  twitter.creator=""

[Params.style.vars]
  highlightColor = "rgb(96,221,108)"

[languages]
  [languages.en]
    title = "Steckschwein"
    subtitle = "An 8bit computer for the 21st century"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Steckschwein"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "hardware"
        name = "Hardware"
        url = "/hardware/"
        weight = 300
      [[languages.en.menu.main]]
        identifier = "software"
        name = "Software"
        url = "/software/"
        weight = 400
      [[languages.en.menu.main]]
        identifier = "impressum"
        name = "Impressum"
        url = "/impressum/"
        weight = 500
