baseurl = "https://www.steckschwein.de/"
languageCode = "en-us"
theme = ["Mainroad"]
paginate = 5
#sectionPagesMenu = "main"


[Params.style.vars]
  highlightColor = "rgb(96,221,108)"

[Params.sidebar]
  home = "left"
  widgets = ["search", "recent",  "taglist", "social"]

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "Steckschwein"
  bitbucket = "steckschwein"

[[Params.widgets.social.custom]]
  title = "YouTube"
  url = "https://www.youtube.com/channel/UCzNO0qQr8fjNhkGxzIM_2vw"

[languages]
  [languages.en]
    title = "Steckschwein"
    subtitle = "An 8bit computer for the 21st century"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "hardware"
        name = "Hardware"
        url = "/hardware/"
        weight = 300
      [[languages.en.menu.main]]
        identifier = "software"
        name = "Software"
        url = "/software/"
        weight = 400
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 450
      [[languages.en.menu.main]]
        identifier = "impressum"
        name = "Impressum"
        url = "/impressum/"
        weight = 500
