baseurl = "https://example.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
SectionPagesMenu = "main"


[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Steckschwein"
    subtitle = "An 8bit computer for the 21st century"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Steckschwein"
      logoHomeLink = "/"

