baseurl = "https://www.steckschwein.de/"
title = "Steckschwein"
languageCode = "en-us"
theme = ["Mainroad"]
paginate = 6

#[markup]
#  goldmark.renderer.unsafe=true

[Params.logo]
  title = "Steckschwein"
  subtitle = "An 8bit computer for the 21st century"

[Params.site]
  ignoreErrors = ["error-remote-getjson"]

[Params]
  description = "An 8bit computer for the 21st century"
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information

[Params.style.vars]
  highlightColor = "rgb(96,221,108)"

[Params.sidebar]
  home = "left"
  widgets = ["recent", "search", "taglist", "social"]

[Params.widgets]
  recent_num = 15

[Params.widgets.social]
  github = "Steckschwein"
  youtube = "@Steckschwein"
  mastodon = "https://mastodon.social/@steckschwein_6502"

[Params.widgets.search]
  url = "/search/"
  [Params.widgets.search.input]
    name = false
    pre = ""