baseurl = "https://www.steckschwein.de/"
title = "Steckschwein"
languageCode = "en-us"
theme = ["Mainroad"]
paginate = 6

[menus]
  [[menus.main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 100

#[markup]
#  goldmark.renderer.unsafe=true

[Params.logo]
  title = "Steckschwein"
  subtitle = "An 8bit computer for the 21st century"

[Params.site]
  ignoreErrors = ["error-remote-getjson"]

[Params]
  description = "An 8bit computer for the 21st century"
  # opengraph = true
  # schema = true
  # twitter_cards = false # Enable Twitter Cards if true
  # readmore = false # Show "Read more" button in list if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  # menuMore = "Show more"
  # readMore = "Read more"
  # readOtherPosts = "Read other posts"

[Params.style.vars]
  highlightColor = "rgb(96,221,108)"

[Params.sidebar]
  home = "left"
  widgets = ["recent", "search", "taglist", "social"]

[Params.widgets]
  recent_num = 15

[Params.widgets.social]
  github = "Steckschwein"
  youtube = "@Steckschwein"
  mastodon = "https://mastodon.social/@steckschwein_6502"

[Params.widgets.search]
  url = "/search/"
  [Params.widgets.search.input]
    name = false
    pre = ""