baseurl = "https://beta.steckschwein.de"
languageCode = "en-us"
theme = "terminal"
paginate = 5
enableRobotsTXT = true
sectionPagesMenu = "main"

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = false

[params.twitter]
  creator = "steckschwein"
  site = ""

[languages]
  [languages.en]
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Steckschwein"
      logoHomeLink = "/"

    