baseurl = "https://www.steckschwein.de/"
languageCode = "en-us"
theme = ["Mainroad"]
paginate = 5
#sectionPagesMenu = "main"
opengraph = true
schema = true
twitter_cards = false

[markup]
  goldmark.renderer.unsafe=true


[Params.site]
  ignoreErrors = ["error-remote-getjson"]

[Params]
  opengraph = true
  schema = true
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information

[Params.style.vars]
  highlightColor = "rgb(96,221,108)"

[Params.sidebar]
  home = "left"
  widgets = ["recent", "search", "taglist", "social"]

[Params.widgets.social]
  # Enable parts of social widget
  github = "Steckschwein"
  youtube = "@Steckschwein"
  mastodon = "@steckschwein_6502@mastodon.social"

[Params.widgets.search]
  url = "/search/"
  [Params.widgets.search.input]
    name = false
    pre = ""

[languages]
  [languages.en]
    title = "Steckschwein"
    subtitle = "An 8bit computer for the 21st century"
    keywords = "8bit,retro,homebrew"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 50

      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/"
        weight = 100
      [[languages.en.menu.main]]
        identifier = "hardware"
        name = "Hardware"
        url = "/hardware/"
        weight = 300
      [[languages.en.menu.main]]
        identifier = "software"
        name = "Software"
        url = "/software/"
        weight = 400
      [[languages.en.menu.main]]
        identifier = "resources"
        name = "Resources"
        url = "/resources/"
        weight = 500



      [[languages.en.menu.main]]
        identifier = "impressum"
        name = "Impressum"
        url = "/impressum/"
        weight = 600
