baseURL = "https://beta.steckschwein.de"
languageCode = "en-us"
title = "Steckschwein"
theme = "ananke"
SectionPagesMenu = "main"
enableRobotsTXT = true

[params]
featured_image = "images/cropped-steckos.jpg"
twitter = "https://twitter.com/steckschwein"
description = "Never trust a computer you did not build yourself."