#baseURL = "http://www.steckschwein.de"
baseURL = "https://steckschwein.github.io"
languageCode = "en-us"
title = "Steckschwein"
theme = "garden"
SectionPagesMenu = "main"

[params]
featured_image = "/images/cropped-steckos.jpg"
twitter = "https://twitter.com/steckschwein"
description = "Never trust a computer you did not build yourself."
